

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "dados_meta";


ALTER SCHEMA "dados_meta" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "mercca_rastreio_whats";


ALTER SCHEMA "mercca_rastreio_whats" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "mercca_rastreio_whats"."whatsapp_anuncio" (
    "telefone" character varying(15) NOT NULL,
    "id_transacao" character varying(255),
    "data_criacao" "date" NOT NULL,
    "source_id" bigint,
    "nome" character varying(255),
    "sobrenome" character varying(255),
    "email" character varying(100),
    "cidade" character varying(255),
    "estado" character varying(255),
    "pais" character varying(50),
    "moeda" character varying(50),
    "valor_venda" numeric(10,0),
    "item_id" "text",
    "item_name" "text",
    "mensagem" "text",
    "cta" "text",
    "ctwaclid" character varying(255),
    "source_url" character varying(255),
    "thumbnail" "text",
    "status" "text",
    "plataforma" "text",
    "processado" character varying(1),
    "data_compra" "date",
    "campaign_name" "text",
    "adset_name" "text",
    "ad_name" "text"
);


ALTER TABLE "mercca_rastreio_whats"."whatsapp_anuncio" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."bot_2" (
    "id" bigint NOT NULL,
    "remoteJid" "text" NOT NULL,
    "botOff" boolean DEFAULT false,
    "timeStamp" timestamp without time zone,
    "Thread" "text",
    "possuiThread" boolean,
    "FollowUp" numeric
);


ALTER TABLE "public"."bot_2" OWNER TO "supabase_admin";


ALTER TABLE "public"."bot_2" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bot_2_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dados_afonso" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric,
    "Compras_meta" numeric,
    "Valor_de_Conversao_meta" bigint
);


ALTER TABLE "public"."dados_afonso" OWNER TO "supabase_admin";


COMMENT ON TABLE "public"."dados_afonso" IS 'This is a duplicate of dados_elinis';



CREATE TABLE IF NOT EXISTS "public"."dados_amanda" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric,
    "Compras_meta" numeric,
    "Valor_de_Conversao_meta" bigint
);


ALTER TABLE "public"."dados_amanda" OWNER TO "supabase_admin";


COMMENT ON TABLE "public"."dados_amanda" IS 'This is a duplicate of dados_top';



CREATE TABLE IF NOT EXISTS "public"."dados_elinis" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric,
    "Compras_meta" numeric,
    "Valor_de_Conversao_meta" bigint
);


ALTER TABLE "public"."dados_elinis" OWNER TO "supabase_admin";


COMMENT ON TABLE "public"."dados_elinis" IS 'This is a duplicate of dados_amanda';



CREATE TABLE IF NOT EXISTS "public"."dados_mercca" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric
);


ALTER TABLE "public"."dados_mercca" OWNER TO "supabase_admin";


CREATE TABLE IF NOT EXISTS "public"."dados_rafa" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric,
    "Compras_meta" numeric,
    "Valor_de_Conversao_meta" numeric
);


ALTER TABLE "public"."dados_rafa" OWNER TO "supabase_admin";


CREATE TABLE IF NOT EXISTS "public"."dados_top" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric,
    "Compras_meta" numeric,
    "Valor_de_Conversao_meta" numeric,
    "conversas_iniciadas" numeric
);


ALTER TABLE "public"."dados_top" OWNER TO "supabase_admin";


COMMENT ON TABLE "public"."dados_top" IS 'This is a duplicate of dados_rafa';



CREATE TABLE IF NOT EXISTS "public"."dados_unirnutri" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text",
    "Leads_meta" numeric,
    "Compras_meta" numeric,
    "Valor_de_Conversao_meta" bigint
);


ALTER TABLE "public"."dados_unirnutri" OWNER TO "supabase_admin";


COMMENT ON TABLE "public"."dados_unirnutri" IS 'This is a duplicate of dados_afonso';



CREATE TABLE IF NOT EXISTS "public"."dados_unirnutri_backup" (
    "Dia" "date" NOT NULL,
    "Campanha" "text" NOT NULL,
    "Conjunto_de_Anuncios" "text" NOT NULL,
    "Anuncio" "text" NOT NULL,
    "Objetivo" "text" NOT NULL,
    "Custo" numeric(10,2) NOT NULL,
    "Leads" numeric,
    "Compras" numeric,
    "Page_View" numeric,
    "Cliques" numeric,
    "Impressoes" numeric,
    "Alcance" numeric,
    "Valor_de_Conversao" numeric(10,2),
    "VV_3s" numeric,
    "VV_25" numeric,
    "VV_50" numeric,
    "VV_75" numeric,
    "VV_95" numeric,
    "ad_id" "text" NOT NULL,
    "id_data" "text" NOT NULL,
    "creative_id" "text",
    "status" "text",
    "Qualificados" numeric,
    "thumbnail_url" "text",
    "permalink_url" "text"
);


ALTER TABLE "public"."dados_unirnutri_backup" OWNER TO "supabase_admin";


COMMENT ON TABLE "public"."dados_unirnutri_backup" IS 'This is a duplicate of dados_rafa';



ALTER TABLE ONLY "mercca_rastreio_whats"."whatsapp_anuncio"
    ADD CONSTRAINT "whatsapp_anuncio_pkey" PRIMARY KEY ("telefone");



ALTER TABLE ONLY "public"."bot_2"
    ADD CONSTRAINT "bot_2_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dados_afonso"
    ADD CONSTRAINT "dados_afonso_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_amanda"
    ADD CONSTRAINT "dados_amanda_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_elinis"
    ADD CONSTRAINT "dados_elinis_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_mercca"
    ADD CONSTRAINT "dados_mercca_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_rafa"
    ADD CONSTRAINT "dados_rafa_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_top"
    ADD CONSTRAINT "dados_top_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_unirnutri_backup"
    ADD CONSTRAINT "dados_unirnutri_pkey" PRIMARY KEY ("id_data");



ALTER TABLE ONLY "public"."dados_unirnutri"
    ADD CONSTRAINT "dados_unirnutri_pkey1" PRIMARY KEY ("id_data");



CREATE INDEX "idx_email" ON "mercca_rastreio_whats"."whatsapp_anuncio" USING "btree" ("email");



CREATE INDEX "idx_id_transacao" ON "mercca_rastreio_whats"."whatsapp_anuncio" USING "btree" ("id_transacao");



CREATE INDEX "idx_source_id_whatsapp" ON "mercca_rastreio_whats"."whatsapp_anuncio" USING "btree" ("source_id");



CREATE POLICY "Enable read access for all users" ON "public"."dados_rafa" FOR SELECT USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON TABLE "public"."bot_2" TO "postgres";
GRANT ALL ON TABLE "public"."bot_2" TO "anon";
GRANT ALL ON TABLE "public"."bot_2" TO "authenticated";
GRANT ALL ON TABLE "public"."bot_2" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bot_2_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."bot_2_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bot_2_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bot_2_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dados_afonso" TO "postgres";
GRANT ALL ON TABLE "public"."dados_afonso" TO "anon";
GRANT ALL ON TABLE "public"."dados_afonso" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_afonso" TO "service_role";



GRANT ALL ON TABLE "public"."dados_amanda" TO "postgres";
GRANT ALL ON TABLE "public"."dados_amanda" TO "anon";
GRANT ALL ON TABLE "public"."dados_amanda" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_amanda" TO "service_role";



GRANT ALL ON TABLE "public"."dados_elinis" TO "postgres";
GRANT ALL ON TABLE "public"."dados_elinis" TO "anon";
GRANT ALL ON TABLE "public"."dados_elinis" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_elinis" TO "service_role";



GRANT ALL ON TABLE "public"."dados_mercca" TO "postgres";
GRANT ALL ON TABLE "public"."dados_mercca" TO "anon";
GRANT ALL ON TABLE "public"."dados_mercca" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_mercca" TO "service_role";



GRANT ALL ON TABLE "public"."dados_rafa" TO "postgres";
GRANT ALL ON TABLE "public"."dados_rafa" TO "anon";
GRANT ALL ON TABLE "public"."dados_rafa" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_rafa" TO "service_role";



GRANT ALL ON TABLE "public"."dados_top" TO "postgres";
GRANT ALL ON TABLE "public"."dados_top" TO "anon";
GRANT ALL ON TABLE "public"."dados_top" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_top" TO "service_role";



GRANT ALL ON TABLE "public"."dados_unirnutri" TO "postgres";
GRANT ALL ON TABLE "public"."dados_unirnutri" TO "anon";
GRANT ALL ON TABLE "public"."dados_unirnutri" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_unirnutri" TO "service_role";



GRANT ALL ON TABLE "public"."dados_unirnutri_backup" TO "postgres";
GRANT ALL ON TABLE "public"."dados_unirnutri_backup" TO "anon";
GRANT ALL ON TABLE "public"."dados_unirnutri_backup" TO "authenticated";
GRANT ALL ON TABLE "public"."dados_unirnutri_backup" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
